config/routes.rb
Rails.application.routes.draw do
 
  get 'users/new'

  root 'static_pages#home'
  get '/services',        to: 'static_pages#services'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'messages#new', as: 'new_message'
  post '/contact',        to: 'messages#create', as: 'create_message'
  get '/signup',          to: 'users#new'
  
  get '/test', to: 'static_pages#test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    include ActiveModel::Model
    attr_accessor :name, :email, :content
    validates :content, presence: true
    validates :name,  presence: true, length: { maximum: 50 }
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 245 },
                      format: { with: EMAIL_REGEX }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                                format: { with: VALID_EMAIL_REGEX },
                                uniqueness: {case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :detect_device_variant
  
  private
    
  def detect_device_variant
    request.variant = :phone if browser.device.mobile?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new
        @message = Message.new
    end
    
    def create
    @message = Message.new message_params

        if @message.valid?
            ContactMailer.contact_me(@message).deliver_now
            flash[:info] = "Thank you for your message!" 
            redirect_to root_path 
        else
            render :new
        end
    end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns title of page
    def full_title(page_title = '')
        base_title = "Social Curation"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_application_layout.html.erb
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <% #debug(params) if Rails.env.development? %>
    </div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-static-bottom">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
        <%= link_to "Social Curation", root_path, method: :get, id: "logo" %>
    </div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Services", services_path, id: "logo-three" %></li>
                <li><%= link_to "Create Your Profile", new_message_path, id: "logo-two" %></li>
                <li><%= link_to "Pricing & About", about_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_menu.html.erb
<div class="menu-header" onclick="openNav()">Menu</div>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <%= link_to "Create Your Profile", new_message_path, id: "logo-four-phone" %>
      <%= link_to "Services", services_path, id: "logo-four-phone" %>
      <%= link_to "Pricing & About", about_path, id: "logo-four-phone" %>
</div>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.body.style.backgroundColor = "white";
}
</script>

app/views/layouts/_phone_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
            <%= render 'layouts/menu' %>
    </div>
    <br>
    <div class="container-center">
        <%= link_to "Social Curation", root_path, method: :get, id: "logo" %>
    </body>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      
  </head>
    <body>
    <%= render 'layouts/application_layout' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="skrollr-body">
        <%= render 'layouts/application_layout' %>
        <%= yield %>
   
    <script type="text/javascript">
	    skrollr.init({
		    forceHeight: false;
		    smoothScrolling: true
	    });
	  </script>
	  </div>
  </body>
</html>

<link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">

app/views/messages/_new.html.erb
<% @message = Message.new %>
<div class="row">
  <div class="col-md-6 col-centered">
    <h5>Interested in any of our services?</h5> 
    <h5>Have questions about what we do?</h5> 
    <h5>Don't hesitate to contact us!</h5>
    &nbsp;
    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
  </div>
</div>

app/views/messages/new.html+phone.erb
<% provide(:title, "Contact") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<div class="row">
  <div class="col-md-6 col-centered">
    <h5>Interested in any of our services?</h5> 
    <h5>Have questions about what we do?</h5> 
    <h5>Don't hesitate to contact us!</h5>
    &nbsp;
    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
  </div>
</div>
</meta>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_products.html.erb
<div class="row">
  <div class="center">
        <h3 id="logo-two"><u>Social Media</u></h3>
  </div>
</div>

<div class="row">
      
      <div class="col-md-6">
          <ul>
            <h4>Social Media Account Creation</h4>
            <li><strong>1 account:</strong> $5</li>
            <li><strong>2 accounts:</strong> $9</li>
            <li><strong>3 accounts:</strong> $13</li>
            <li><strong>4 accounts:</strong> $15</li>
          </ul>
      </div>
        
      
      <div class="col-md-6">
          <ul>
            <h4>Social Media Account Curation(per account)</h4>
            <li><strong>1 week:</strong> $20</li>
            <li><strong>2 weeks:</strong> $38</li>
            <li><strong>3 weeks:</strong> $58</li>
            <li><strong>4 weeks:</strong> $78</li>
          </ul>
      </div> 
      
    </div>
    
<br />

    <div class="row">
      <div class="center">
        <h3 id="logo-two"><u>Website & SEO Improvement</u></h3>
      </div>
    </div>
    
    <div class="row">
      
      <div class="col-md-6">
          <ul>
            <strong><h4>SEO Analysis & Improvement:</h4></strong>
            <li><strong>Website Analysis:</strong> Free(up to 10 pages)</li>
            <li><strong>SEO Update(per page):</strong> $15</li>
            <li><strong>New SEO Implementation(per page):</strong> $20</li>
          </ul>
      </div>
      
      <div class="col-md-6">
          <ul>
            <strong><h4>Website Optimization:</h4></strong>
            <li><strong>Front end website changes:</strong> $45/hr</li>
            <li><strong>Back end website changes(Ruby on Rails only):</strong> $85/hr</li>
          </ul>
      </div> 
      
    </div>

app/views/static_pages/_serv2.html.erb
<div class="row">
    
    <div class="col-md-6">
        <div class="vertc">
            <%= image_tag('SEO-bkg-phone.jpg') %>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="center">
            <h3>
                <div><u>SEO Analysis & Improvement</u></div>
            </h3>
            <p>
                Not many people checking out your website? If you google it does it even come up? Well guess what motherfucker, we'll make it happen! Our team(literally just me) has been learing and implementing the best and most up to date SEO practices for years! 
            </p>
        </div>
    &nbsp;
        <h4>SEO Analysis & Improvement includes:</h4>
        <ul>
            <li><strong>Preliminary SEO analysis for your full website</strong></li>
            <li><strong>Improvement of out dated SEO practices</strong></li>
            <li><strong>Implementation of current best SEO practices</strong></li>
            <li><strong>Creation of linked social media accounts</strong></li>
            <li><strong>Social media integration in order to create orgainc backlinks and website visits</strong></li>
        </ul>
        &nbsp;
    </div>
    
</div>

app/views/static_pages/_serv4.html.erb
<div class="row">
    
    <div class="col-md-6">
        <div class="vertc">
            <%= image_tag('social-media-phone.jpg') %>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="center">
            <h3>
                <div><u>Social Media Curation</u></div>
            </h3>
            <p>
                Want more Instagram followers? More Facebook friends? I got you. Besides writing code alone in my one room apt, curating my 45 individual social media personalities is literally the only thing that makes me believe for a second that I have friends. And thats why I'm so good at it.
            </p>
        </div>
        <ul>
            <li><strong>Not enough Facebook friends?</strong> I'll make you seem more fun, post some engaging stuff, join like 16 Facebook groups and constantly start meaningful threads in them. You'll be so popular you won't ever have time for your real friends!</li>
            <li><strong>Want Instagram followers?</strong> I got you! Not only will I collect and analyze your Instagram data for you, I'll post in a consistent manner following engagment trends to maximize your likes and steadily gain followers.</li>
            <li><strong>Is that putting too much thought into social media?</strong> Only if you don't want to be good at it!</li>
            <li><strong>Guess what else?</strong> Linkedin: Done. Youtube: Super Done. Literally every form of social media: Done. Anything I don't know: I'll learn it, implement best practices, and make your account successful! I'll even make the accounts!</li>
        </ul>
    &nbsp;
    </div>
    
</div>

app/views/static_pages/_slide.html.erb
<div class="center">
                
                        <div class="flexslider">
                                <ul class="slides">
                                        <li>
                                                <%= link_to image_tag('christine-fb.png'), root_path(:anchor=> "social") %>
                                                <h1><%= link_to "Social Media Profile Creation", root_path(:anchor=> "social") %></h1>
                                        </li>
                                        <li>
                                                <%= link_to image_tag('SEO-bkg.jpg'), root_path(:anchor=> "SEO") %>
                                                <h1><%= link_to "SEO Analysis & Improvement", root_path(:anchor=> "SEO") %></h1>
                                        </li>
                                        <li>
                                                <%= link_to image_tag('Website-image.jpg'), root_path(:anchor=> "website") %>
                                                <h1><%= link_to "Website Optimization", root_path(:anchor=> "website") %></h1>
                                        </li>
                                        <li>
                                                <%= link_to image_tag('social-media.jpg'), root_path(:anchor=> "social-med") %>
                                                <h1><%= link_to "Social Media Curation", root_path(:anchor=> "social-med") %></h1>
                                        </li>
                                </ul>
 
                        </div>

</div>

app/views/static_pages/_svg1.html.erb
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
 "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg id="mySVG" version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="799.000000pt" height="485.000000pt" viewBox="0 0 799.000000 485.000000"
 preserveAspectRatio="xMidYMid meet">
<metadata>
Created by potrace 1.15, written by Peter Selinger 2001-2017
</metadata>
<g transform="translate(0.000000,485.000000) scale(0.100000,-0.100000)"
fill="#000000" stroke="none">
<path style="fill:none;stroke:#333333;stroke-width:7;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:6000;stroke-dashoffset:0"
				data-0="stroke-dashoffset:6000;" data-end="stroke-dashoffset:0;"
d="M7190 3426 c-204 -45 -354 -139 -418 -261 -57 -108 -25 -246 78 -338
93 -84 225 -129 380 -130 152 -2 272 38 358 117 61 56 86 108 86 176 -1 63
-11 85 -62 142 -130 144 -422 149 -529 9 -38 -50 -44 -134 -12 -175 12 -16 37
-35 55 -42 39 -16 120 -19 129 -4 4 6 -8 10 -28 10 -48 0 -97 18 -129 48 -59
55 -26 153 67 201 45 24 61 26 165 26 136 -1 208 -23 271 -86 52 -52 66 -107
45 -174 -42 -135 -185 -205 -421 -205 -218 0 -368 68 -431 196 -22 46 -26 64
-22 121 2 39 12 85 23 108 45 93 171 179 325 221 96 27 308 24 413 -4 175 -48
323 -155 383 -277 26 -54 29 -70 29 -155 0 -83 -4 -103 -27 -153 -57 -121
-205 -223 -396 -274 -86 -23 -116 -26 -267 -26 -182 -1 -280 14 -465 70 -76
22 -528 190 -539 200 -3 2 3 20 13 41 80 165 -35 338 -269 408 -72 21 -236 24
-311 5 -49 -12 -53 -11 -88 13 -93 63 -246 90 -371 67 -130 -24 -244 -103
-288 -200 -17 -35 -22 -67 -23 -136 l0 -90 -133 -67 c-154 -78 -264 -116 -365
-124 -151 -13 -220 36 -261 183 -5 19 -1 23 32 28 163 25 269 62 358 126 85
61 111 144 60 194 -19 20 -34 25 -73 25 -98 0 -257 -69 -316 -137 -14 -15 -41
-65 -62 -109 l-36 -81 -103 -7 c-105 -7 -145 0 -145 27 0 30 -63 142 -107 188
-79 85 -207 132 -311 114 -111 -18 -111 -133 0 -212 92 -66 173 -97 302 -118
49 -8 91 -17 94 -20 10 -9 -20 -90 -45 -123 -65 -86 -199 -101 -378 -44 -55
18 -154 61 -220 95 l-120 63 0 85 c-1 69 -5 94 -27 141 -33 72 -94 130 -177
170 -57 27 -80 32 -168 36 -124 6 -174 -6 -261 -58 -72 -44 -121 -50 -212 -29
-183 42 -416 -40 -495 -176 -32 -54 -42 -128 -23 -174 14 -34 14 -33 10 35 -3
58 0 76 20 114 46 86 152 143 298 159 72 8 214 1 259 -14 18 -5 18 -6 0 -43
-24 -49 -42 -147 -36 -194 3 -21 1 -40 -3 -43 -5 -3 -60 -12 -122 -19 -62 -8
-151 -27 -198 -42 -106 -33 -160 -36 -191 -9 l-22 20 7 -20 c19 -47 18 -52
-11 -63 -15 -5 -109 -40 -207 -76 -204 -75 -406 -135 -546 -162 -140 -26 -378
-24 -485 4 -183 49 -331 155 -392 280 -24 50 -28 69 -28 148 0 83 3 96 34 157
45 89 141 186 223 226 97 47 169 63 318 68 344 13 570 -110 601 -326 l8 -56
-3 66 c-8 153 -118 256 -342 321 -68 20 -101 23 -244 23 -154 -1 -170 -3 -244
-28 -179 -63 -301 -189 -361 -375 -53 -163 66 -364 277 -466 114 -56 224 -83
387 -97 117 -9 161 -8 286 7 82 10 261 69 410 134 77 34 188 82 247 107 l108
44 47 -40 c144 -120 382 -188 633 -178 l135 5 79 -40 c98 -49 197 -62 271 -34
25 10 48 22 51 28 4 6 -1 6 -14 -1 -47 -25 -254 4 -308 43 -14 11 -8 16 47 36
89 31 159 68 190 97 26 24 28 24 52 8 31 -20 53 -52 65 -96 10 -33 10 -33 11
-6 1 31 -21 81 -51 113 -19 22 -19 22 16 70 19 27 43 59 53 72 l18 24 90 -45
c195 -96 332 -137 460 -137 68 0 90 4 134 26 57 29 103 87 121 154 l9 35 118
0 117 0 12 -48 c26 -101 91 -159 196 -173 96 -13 270 34 469 127 69 33 128 59
132 59 4 0 14 -15 23 -32 9 -18 32 -52 50 -74 l33 -42 -20 -18 c-30 -27 -59
-88 -58 -121 1 -28 1 -28 9 4 6 28 64 113 76 113 3 0 53 -24 112 -54 59 -29
124 -59 145 -66 20 -6 37 -13 37 -16 0 -7 -62 -35 -107 -49 -113 -34 -217 -27
-248 18 -8 12 -15 17 -15 11 0 -23 57 -63 104 -74 67 -15 123 -5 241 42 l100
40 102 -6 c241 -15 510 53 635 161 34 29 71 53 82 53 12 0 50 -14 86 -31 134
-64 419 -178 515 -207 294 -89 585 -73 825 44 123 61 230 163 280 268 30 63
32 75 28 141 -11 164 -131 323 -308 407 -52 25 -125 53 -162 62 -78 19 -228
20 -308 2z m-1718 -156 c57 -22 123 -69 111 -80 -4 -4 -37 -17 -73 -29 -56
-20 -254 -116 -483 -234 -73 -38 -76 -37 -88 27 -41 223 278 413 533 316z
m-2669 4 c168 -43 267 -150 267 -289 0 -85 -6 -90 -66 -66 -28 10 -137 64
-244 118 -107 55 -226 110 -265 123 -38 12 -74 26 -78 30 -12 11 66 60 130 80
72 23 176 25 256 4z m777 -60 c69 -21 114 -50 173 -113 44 -47 97 -139 97
-168 0 -32 -178 2 -287 53 -33 16 -85 54 -120 89 -82 79 -83 113 -7 140 51 18
79 18 144 -1z m1010 -12 c28 -23 30 -84 3 -121 -50 -67 -225 -142 -367 -157
-77 -8 -78 -6 -47 76 25 66 61 112 115 149 93 64 248 92 296 53z m1487 -52
c67 -23 153 -91 178 -141 21 -40 19 -135 -5 -188 -17 -36 -24 -42 -43 -38 -12
2 -74 18 -137 35 -63 17 -163 38 -221 48 l-106 17 -6 82 c-3 60 -12 99 -30
140 -19 39 -23 57 -14 60 30 10 81 13 197 10 98 -2 138 -7 187 -25z m-3560
-36 c107 -35 257 -101 399 -175 65 -34 122 -65 126 -68 14 -13 -68 -141 -90
-141 -5 0 -47 18 -93 39 -140 66 -339 111 -491 111 l-67 0 -7 46 c-12 80 9
166 53 215 16 19 45 15 170 -27z m3163 1 c27 -43 46 -147 36 -197 l-7 -38 -66
0 c-157 0 -364 -47 -512 -117 -54 -26 -79 -33 -90 -26 -23 14 -81 102 -81 122
1 11 62 45 193 109 241 116 263 125 367 156 118 35 134 34 160 -9z m-3359
-327 c43 -74 124 -162 179 -194 16 -10 30 -21 30 -25 0 -13 -131 -22 -221 -15
-122 9 -228 38 -334 90 -80 40 -167 108 -154 121 3 2 63 20 135 40 108 30 196
45 306 54 11 1 31 -24 59 -71z m335 37 c93 -24 264 -99 264 -116 0 -5 -39 -35
-86 -66 -86 -55 -154 -83 -203 -83 -44 1 -109 37 -173 97 -59 56 -148 166
-148 183 0 27 219 17 346 -15z m3037 29 c8 -9 -29 -80 -66 -126 -40 -50 -136
-124 -192 -149 -35 -16 -56 -19 -87 -14 -42 7 -145 57 -227 109 l-43 28 37 25
c111 76 312 127 511 132 33 0 63 -2 67 -5z m214 -19 c91 -17 264 -64 276 -75
11 -10 -86 -86 -153 -120 -120 -60 -272 -90 -449 -90 l-116 1 45 37 c88 71
157 148 184 205 l27 57 53 0 c30 0 90 -7 133 -15z"/>
<path
style="fill:none;stroke:#333333;stroke-width:7;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:6000;stroke-dashoffset:0"
				data-0="stroke-dashoffset:6000;" data-end="stroke-dashoffset:0;
d="M616 3238 c-156 -21 -276 -129 -276 -249 0 -176 203 -298 475 -286
189 8 307 63 385 179 47 71 54 100 9 38 -44 -61 -74 -85 -154 -125 -123 -62
-311 -83 -438 -50 -227 59 -328 244 -204 373 121 127 402 136 493 16 67 -87
27 -178 -93 -210 l-48 -13 43 0 c89 -2 152 48 159 126 6 60 -20 103 -91 150
-72 49 -155 65 -260 51z"/>
</g>
</svg>

<svg id="mySVG">
  <path style="fill:none;stroke:red;stroke-width:7;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:3000;stroke-dashoffset:0"
data-0="stroke-dashoffset:3000;" data-end="stroke-dashoffset:-10000;"
  d="M150 0 L75 200 L225 200 Z"/>
</svg>

<script type="text/javascript">
	skrollr.init({
		forceHeight: false
	});
	</script>

app/views/static_pages/_svg90.html.erb
<svg id="mySVG" class="flip90">
  <path fill="none" stroke="white" stroke-width="3" id="trii" d="
		M125.815,15.703c0-2.23,3.127-14.462,20.023-14.462c19.75,0,24.97,19.541,24.97,26.143c0,7.52-2.836,26.375-25.336,26.375
		s-40.78-39.263-79.5-39.263c-23.613,0-32.28,38.911-49.905,38.911c-9.75,0-14.875-5.625-14.875-11.875
		c0-6.625,4.438-11.125,11.563-11.125c6.592,0,9.562,4.75,9.562,9.25"/>
</svg>



<script>
  /* SVG draw on scroll */
// Get the id of the <path> element and the length of <path>
var trii = document.getElementById("trii");
var length = trii.getTotalLength();

// The start position of the drawing
trii.style.strokeDasharray = length;

// Hide the triangle by offsetting dash. Remove this line to show the triangle before scroll draw
trii.style.strokeDashoffset = length;

// Find scroll percentage on scroll (using cross-browser properties), and offset dash same amount as percentage scrolled
window.addEventListener("scroll", myFunction);

function myFunction() {
var scrollpercent = (document.body.scrollTop + document.documentElement.scrollTop) / (document.documentElement.scrollHeight - document.documentElement.clientHeight);
// multiply scrollpercent by # to increase speed
  var draw = length * (scrollpercent * 7.5);
  
  // Reverse the drawing (when scrolling upwards)
  trii.style.strokeDashoffset = length - draw;
}
</script>

app/views/static_pages/_svgl.html.erb
<svg id="mySVG" class="flip">
  <path fill="none" stroke="white" stroke-width="3" id="triangle" d="
		M125.815,15.703c0-2.23,3.127-14.462,20.023-14.462c19.75,0,24.97,19.541,24.97,26.143c0,7.52-2.836,26.375-25.336,26.375
		s-40.78-39.263-79.5-39.263c-23.613,0-32.28,38.911-49.905,38.911c-9.75,0-14.875-5.625-14.875-11.875
		c0-6.625,4.438-11.125,11.563-11.125c6.592,0,9.562,4.75,9.562,9.25"/>
</svg>


<script>
  /* SVG draw on scroll */
// Get the id of the <path> element and the length of <path>
var triangle = document.getElementById("triangle");
var length = triangle.getTotalLength();

// The start position of the drawing
triangle.style.strokeDasharray = length;

// Hide the triangle by offsetting dash. Remove this line to show the triangle before scroll draw
triangle.style.strokeDashoffset = length;

// Find scroll percentage on scroll (using cross-browser properties), and offset dash same amount as percentage scrolled
window.addEventListener("scroll", myFunction);

function myFunction() {
var scrollpercent = (document.body.scrollTop + document.documentElement.scrollTop) / (document.documentElement.scrollHeight - document.documentElement.clientHeight);
// multiply scrollpercent by # to increase speed
  var draw = length * (scrollpercent * 7.5);
  
  // Reverse the drawing (when scrolling upwards)
  triangle.style.strokeDashoffset = length - draw;
}
</script>

app/views/static_pages/_svgr.html.erb
<svg id="mySVG">
  <path fill="none" stroke="white" stroke-width="3" id="tri" d="
		M125.815,15.703c0-2.23,3.127-14.462,20.023-14.462c19.75,0,24.97,19.541,24.97,26.143c0,7.52-2.836,26.375-25.336,26.375
		s-40.78-39.263-79.5-39.263c-23.613,0-32.28,38.911-49.905,38.911c-9.75,0-14.875-5.625-14.875-11.875
		c0-6.625,4.438-11.125,11.563-11.125c6.592,0,9.562,4.75,9.562,9.25"/>
</svg>



<script>
  /* SVG draw on scroll */
// Get the id of the <path> element and the length of <path>
var tri = document.getElementById("tri");
var length = tri.getTotalLength();

// The start position of the drawing
tri.style.strokeDasharray = length;

// Hide the triangle by offsetting dash. Remove this line to show the triangle before scroll draw
tri.style.strokeDashoffset = length;

// Find scroll percentage on scroll (using cross-browser properties), and offset dash same amount as percentage scrolled
window.addEventListener("scroll", myFunction);

function myFunction() {
var scrollpercent = (document.body.scrollTop + document.documentElement.scrollTop) / (document.documentElement.scrollHeight - document.documentElement.clientHeight);
// multiply scrollpercent by # to increase speed
  var draw = length * (scrollpercent * 7.5);
  
  // Reverse the drawing (when scrolling upwards)
  tri.style.strokeDashoffset = length - draw;
}
</script>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>